In [1]:
!pip install -U -q transformers peft bitsandbytes
!pip install -q --upgrade transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 32.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.7/69.7 MB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 47.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 52.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 39.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 71.6 MB/s eta 0:00:00

In [2]:
!pip install -q python-dotenv

In [9]:
!pip install -q evaluate
!pip install -q bert_score

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 2.2 MB/s eta 0:00:00

In [3]:
from google.colab import drive

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!cp /content/drive/MyDrive/project_summary_test/dataloader/config.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/llm_loader.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/main.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/summarization_dataset.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/summarizer.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/util.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/"test-data.csv" /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/summarization_pipeline.py /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/.env /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/"test-data-out-simple-dsp_prompt.csv" /content
!cp /content/drive/MyDrive/project_summary_test/dataloader/evaluation.py /content

In [10]:
import pandas as pd
from summarization_dataset import BaseAbstractDataset, AdvancedAbstractDataset
from summarizer import SummarizerLLM
import config
from summarization_pipeline import SummarizationPipeline
from evaluation import Evaluation, Evaluation_df

In [ ]:
data = pd.read_csv("test-data.csv")

In [ ]:
model_name = "Qwen/Qwen2.5-0.5B-Instruct"

In [ ]:
access_token = "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"

In [ ]:
pipe = SummarizationPipeline(model_name=model_name, load_type="simple",token=access_token, batch_size=5)

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

In [ ]:
out = pipe.run(dataset_class=AdvancedAbstractDataset,
               dataset=data,
               prompt=config.dsp_prompt
              )

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

In [ ]:
out

,urls,titles,keywords,abstracts,one_sentence_summary,generated-summary
0,https://openreview.net/forum?id=HJ0NvFzxl,Learning Graphical State Transitions,Natural language processing; Deep learning; Su...,Graph-structured data is important in modeling...,I introduce a set of differentiable graph tran...,"The GGT-NN, an extension of GGS-NNs using grap..."
1,https://openreview.net/forum?id=H1W1UN9gg,Deep Information Propagation,Theory; Deep learning,We study the behavior of untrained neural netw...,We predict whether randomly initialized neural...,Deep learning models with random weights exhib...
2,https://openreview.net/forum?id=ryMxXPFex,Discrete Variational Autoencoders,Deep learning; Unsupervised Learning,Probabilistic models with discrete latent vari...,We present a novel method to train a class of ...,Discrete Variational Autoencoders (DVAEs) enab...
3,https://openreview.net/forum?id=Hkg8bDqee,Introspection:Accelerating Neural Network Trai...,Computer vision; Deep learning; Optimization,Neural Networks are function approximators tha...,Acceleration of training by performing weight ...,Introducing weight-evolution learning to accel...
4,https://openreview.net/forum?id=rJeKjwvclx,Dynamic Coattention Networks For Question Answ...,Natural language processing; Deep learning; Ap...,Several deep learning models have been propose...,An end-to-end dynamic neural network model for...,"Dynamic Coattention Networks (DCNs), introduce..."
5,https://openreview.net/forum?id=B1kJ6H9ex,Combining policy gradient and Q-learning,Deep learning; Reinforcement Learning,Policy gradient is an efficient technique for ...,We combine a policy gradient style update with...,Combining policy gradient and off-policy Q-lea...
6,https://openreview.net/forum?id=H1oyRlYgg,On Large-Batch Training for Deep Learning: Gen...,Deep learning; Optimization,The stochastic gradient descent (SGD) method a...,We present numerical evidence for the argument...,"On large-batch training in deep learning, we o..."
7,https://openreview.net/forum?id=Bk8BvDqex,Metacontrol for Adaptive Imagination-Based Opt...,Deep learning; Reinforcement Learning; Optimiz...,Many machine learning systems are built to sol...,"We present a ""metacontroller"" neural architect...",A novel metacontroller learns to adaptively al...
8,https://openreview.net/forum?id=S1di0sfgl,Hierarchical Multiscale Recurrent Neural Networks,Natural language processing; Deep learning,Learning both hierarchical and temporal repres...,Propose a recurrent neural network architectur...,Hierarchical multiscale recurrent neural netwo...
9,https://openreview.net/forum?id=BJhZeLsxx,What does it take to generate natural textures?,Deep learning; Unsupervised Learning,Natural image generation is currently one of t...,Natural textures of high perceptual quality ca...,One sentence summary: Our study shows that nat...
10,https://openreview.net/forum?id=Byj72udxe,Pointer Sentinel Mixture Models,Natural language processing; Deep learning,Recent neural network sequence models with sof...,Pointer sentinel mixture models provide a meth...,Pointer Sentinel Mixture Models address the li...
11,https://openreview.net/forum?id=HkNRsU5ge,Sigma Delta Quantized Networks,Computer vision; Deep learning; Applications,Deep neural networks can be obscenely wasteful...,A deep neural network that saves computation o...,Sigma-Delta networks optimize deep neural netw...
12,https://openreview.net/forum?id=SJkXfE5xx,Revisiting Classifier Two-Sample Tests,Theory; Unsupervised Learning,The goal of two-sample tests is to assess whet...,Modern binary classifiers can be easily turned...,This paper investigates Classifier Two-Sample ...
13,https://openreview.net/forum?id=rkpACe1lx,HyperNetworks,Natural language processing; Deep learning; Su...,This work explores hypernetworks: an approach ...,We train a small RNN to generate weights for a...,"Hypernetworks, employing a shared hypernetwork..."
14,https://openreview.net/forum?id=B1YfAfcgl,Entropy-SGD: Biasing Gradient Descent Into Wid...,Deep learning; Optimization,This paper proposes a new optimization algorit...,This paper focuses on developing new optimizat...,Entropy-SGD introduces a novel objective funct...
15,https://openreview.net/forum?id=B1ElR4cgg,Adversarially Learned Inference,Computer vision; Deep learning; Unsupervised L...,We introduce the adversarially learned inferen...,We present and adverserially trained generativ...,Adversarially learned inference models combine...
16,https://openreview.net/forum?id=Bkab5dqxe,A Compositional Object-Based Approach to Learn...,Deep learning; Unsupervised Learning,"We present the Neural Physics Engine (NPE), a ...",We propose a factorization of a physical scene...,A novel deep-learning framework called Neural ...
17,https://openreview.net/forum?id=r1LXit5ee,Episodic Exploration for Deep Deterministic Po...,Deep learning; Reinforcement Learning; Games,We consider scenarios from the real-time strat...,We propose a new reinforcement learning algori...,"Deep learning techniques, particularly through..."
18,https://openreview.net/forum?id=SyWvgP5el,EPOpt: Learning Robust Neural Network Policies...,Reinforcement Learning; Applications,Sample complexity and safety are major challen...,An ensemble optimization approach to help tran...,EPOpt introduces an ensemble approach combinin...
19,https://openreview.net/forum?id=SJGCiw5gl,Pruning Convolutional Neural Networks for Reso...,Deep learning; Transfer Learning,We propose a new formulation for pruning convo...,New approach for removing unnecessary conv neu...,We introduce a novel pruning method for convol...

In [ ]:
out.iloc[0]["generated-summary"]

NameError: name 'out' is not defined

In [ ]:
out.iloc[19]["generated-summary"]

'We introduce a novel pruning method for convolutional neural networks using interleaved greedy criteria-based pruning and backpropagation, demonstrating superior performance over existing methods for both transfer learning and image classification tasks.'

In [ ]:
out.iloc[16]["abstracts"]

"We present the Neural Physics Engine (NPE), a framework for learning simulators of intuitive physics that naturally generalize across variable object count and different scene configurations. We propose a factorization of a physical scene into composable object-based representations and a neural network architecture whose compositional structure factorizes object dynamics into pairwise interactions. Like a symbolic physics engine, the NPE is endowed with generic notions of objects and their interactions; realized as a neural network, it can be trained via stochastic gradient descent to adapt to specific object properties and dynamics of different worlds. We evaluate the efficacy of our approach on simple rigid body dynamics in two-dimensional worlds. By comparing to less structured architectures, we show that the NPE's compositional representation of the structure in physical interactions improves its ability to predict movement, generalize across variable object count and different scene configurations, and infer latent properties of objects such as mass."

In [ ]:
import pandas as pd

In [11]:
test = pd.read_csv("test-data-out-simple-dsp_prompt.csv")

In [ ]:
def get_word_count(df, df_col_name:str, new_col_name:str):
  df[new_col_name] = df[df_col_name].apply(lambda x:len(str(x).split(" ")))
  return df

In [ ]:
df = get_word_count(test, "generated-summary", "word-count")
df

,urls,titles,keywords,abstracts,one_sentence_summary,generated-summary,word-count
0,https://openreview.net/forum?id=HJ0NvFzxl,Learning Graphical State Transitions,Natural language processing; Deep learning; Su...,Graph-structured data is important in modeling...,I introduce a set of differentiable graph tran...,The Gated Graph Transformer Neural Network ext...,25
1,https://openreview.net/forum?id=H1W1UN9gg,Deep Information Propagation,Theory; Deep learning,We study the behavior of untrained neural netw...,We predict whether randomly initialized neural...,Human-centered artificial intelligence (AI) sy...,28
2,https://openreview.net/forum?id=ryMxXPFex,Discrete Variational Autoencoders,Deep learning; Unsupervised Learning,Probabilistic models with discrete latent vari...,We present a novel method to train a class of ...,Human-Computer Interaction (HCI) Research: A N...,21
3,https://openreview.net/forum?id=Hkg8bDqee,Introspection:Accelerating Neural Network Trai...,Computer vision; Deep learning; Optimization,Neural Networks are function approximators tha...,Acceleration of training by performing weight ...,"Given the title ""Introspection: Accelerating N...",48
4,https://openreview.net/forum?id=rJeKjwvclx,Dynamic Coattention Networks For Question Answ...,Natural language processing; Deep learning; Ap...,Several deep learning models have been propose...,An end-to-end dynamic neural network model for...,Human-computer dynamic coattention networks im...,13
5,https://openreview.net/forum?id=B1kJ6H9ex,Combining policy gradient and Q-learning,Deep learning; Reinforcement Learning,Policy gradient is an efficient technique for ...,We combine a policy gradient style update with...,Human-computer interaction through policy grad...,10
6,https://openreview.net/forum?id=H1oyRlYgg,On Large-Batch Training for Deep Learning: Gen...,Deep learning; Optimization,The stochastic gradient descent (SGD) method a...,We present numerical evidence for the argument...,Human: Generate a short summary from the title...,103
7,https://openreview.net/forum?id=Bk8BvDqex,Metacontrol for Adaptive Imagination-Based Opt...,Deep learning; Reinforcement Learning; Optimiz...,Many machine learning systems are built to sol...,"We present a ""metacontroller"" neural architect...",Metacontrol enables adaptive imagination-based...,20
8,https://openreview.net/forum?id=S1di0sfgl,Hierarchical Multiscale Recurrent Neural Networks,Natural language processing; Deep learning,Learning both hierarchical and temporal repres...,Propose a recurrent neural network architectur...,Human-computer interaction through natural lan...,8
9,https://openreview.net/forum?id=BJhZeLsxx,What does it take to generate natural textures?,Deep learning; Unsupervised Learning,Natural image generation is currently one of t...,Natural textures of high perceptual quality ca...,Human skin textures are generated using a sing...,13
10,https://openreview.net/forum?id=Byj72udxe,Pointer Sentinel Mixture Models,Natural language processing; Deep learning,Recent neural network sequence models with sof...,Pointer sentinel mixture models provide a meth...,Human language models can leverage longer cont...,23
11,https://openreview.net/forum?id=HkNRsU5ge,Sigma Delta Quantized Networks,Computer vision; Deep learning; Applications,Deep neural networks can be obscenely wasteful...,A deep neural network that saves computation o...,Human-computer interaction through deep learni...,14
12,https://openreview.net/forum?id=SJkXfE5xx,Revisiting Classifier Two-Sample Tests,Theory; Unsupervised Learning,The goal of two-sample tests is to assess whet...,Modern binary classifiers can be easily turned...,Revisiting Classifier Two-Sample Tests explore...,25
13,https://openreview.net/forum?id=rkpACe1lx,HyperNetworks,Natural language processing; Deep learning; Su...,This work explores hypernetworks: an approach ...,We train a small RNN to generate weights for a...,Human-Retrieval hypernetworks leverage one net...,18
14,https://openreview.net/forum?id=B1YfAfcgl,Entropy-SGD: Biasing Gradient Descent Into Wid...,Deep learning; Optimization,This paper proposes a new optimization algorit...,This paper focuses on developing new optimizat...,Find local extremum points with low generaliza...,14
15,https://openreview.net/forum?id=B1ElR4cgg,Adversarially Learned Inference,Computer vision; Deep learning; Unsupervised L...,We introduce the adversarially learned inferen...,We present and adverserially trained generativ...,Write a program in Python that takes a list of...,17
16,https://openreview.net/forum?id=Bkab5dqxe,A Compositional Object-Based Approach to Learn...,Deep learning; Unsupervised Learning,"We present the Neural Physics Engine (NPE), a ...",We propose a factorization of a physical scene...,Human-computer interaction through deep reinfo...,10
17,https://openreview.net/forum?id=r1LXit5ee,Episodic Exploration for Deep Deterministic Po...,Deep learning; Reinforcement Learning; Games,We consider scenarios from the real-time strat...,We propose a new reinforcement learning algori...,Human: Summary: The paper proposes a novel app...,31
18,https://openreview.net/forum?id=SyWvgP5el,EPOpt: Learning Robust Neural Network Policies...,Reinforcement Learning; Applications,Sample complexity and safety are major challen...,An ensemble optimization approach to help tran...,Human-Agent collaboration through model ensemb...,13
19,https://openreview.net/forum?id=SJGCiw5gl,Pruning Convolutional Neural Networks for Reso...,Deep learning; Transfer Learning,We propose a new formulation for pruning convo...,New approach for removing unnecessary conv neu...,Pruning convolutional neural networks for reso...,21

In [ ]:
import spacy
def get_sentence_count(df, df_col_name:str, new_col_name:str):
  nlp = spacy.load('en_core_web_sm')  # بارگذاری مدل زبان انگلیسی
  df[new_col_name] = df[df_col_name].apply(lambda x:len([sent.text for sent in nlp(str(x)).sents]))
  return df

In [ ]:
t = get_sentence_count(test, "generated-summary", "sentence-count")
t

,urls,titles,keywords,abstracts,one_sentence_summary,generated-summary,word-count,sentence-count
0,https://openreview.net/forum?id=HJ0NvFzxl,Learning Graphical State Transitions,Natural language processing; Deep learning; Su...,Graph-structured data is important in modeling...,I introduce a set of differentiable graph tran...,The Gated Graph Transformer Neural Network ext...,25,1
1,https://openreview.net/forum?id=H1W1UN9gg,Deep Information Propagation,Theory; Deep learning,We study the behavior of untrained neural netw...,We predict whether randomly initialized neural...,Human-centered artificial intelligence (AI) sy...,28,1
2,https://openreview.net/forum?id=ryMxXPFex,Discrete Variational Autoencoders,Deep learning; Unsupervised Learning,Probabilistic models with discrete latent vari...,We present a novel method to train a class of ...,Human-Computer Interaction (HCI) Research: A N...,21,1
3,https://openreview.net/forum?id=Hkg8bDqee,Introspection:Accelerating Neural Network Trai...,Computer vision; Deep learning; Optimization,Neural Networks are function approximators tha...,Acceleration of training by performing weight ...,"Given the title ""Introspection: Accelerating N...",48,1
4,https://openreview.net/forum?id=rJeKjwvclx,Dynamic Coattention Networks For Question Answ...,Natural language processing; Deep learning; Ap...,Several deep learning models have been propose...,An end-to-end dynamic neural network model for...,Human-computer dynamic coattention networks im...,13,1
5,https://openreview.net/forum?id=B1kJ6H9ex,Combining policy gradient and Q-learning,Deep learning; Reinforcement Learning,Policy gradient is an efficient technique for ...,We combine a policy gradient style update with...,Human-computer interaction through policy grad...,10,1
6,https://openreview.net/forum?id=H1oyRlYgg,On Large-Batch Training for Deep Learning: Gen...,Deep learning; Optimization,The stochastic gradient descent (SGD) method a...,We present numerical evidence for the argument...,Human: Generate a short summary from the title...,103,7
7,https://openreview.net/forum?id=Bk8BvDqex,Metacontrol for Adaptive Imagination-Based Opt...,Deep learning; Reinforcement Learning; Optimiz...,Many machine learning systems are built to sol...,"We present a ""metacontroller"" neural architect...",Metacontrol enables adaptive imagination-based...,20,1
8,https://openreview.net/forum?id=S1di0sfgl,Hierarchical Multiscale Recurrent Neural Networks,Natural language processing; Deep learning,Learning both hierarchical and temporal repres...,Propose a recurrent neural network architectur...,Human-computer interaction through natural lan...,8,1
9,https://openreview.net/forum?id=BJhZeLsxx,What does it take to generate natural textures?,Deep learning; Unsupervised Learning,Natural image generation is currently one of t...,Natural textures of high perceptual quality ca...,Human skin textures are generated using a sing...,13,1
10,https://openreview.net/forum?id=Byj72udxe,Pointer Sentinel Mixture Models,Natural language processing; Deep learning,Recent neural network sequence models with sof...,Pointer sentinel mixture models provide a meth...,Human language models can leverage longer cont...,23,1
11,https://openreview.net/forum?id=HkNRsU5ge,Sigma Delta Quantized Networks,Computer vision; Deep learning; Applications,Deep neural networks can be obscenely wasteful...,A deep neural network that saves computation o...,Human-computer interaction through deep learni...,14,1
12,https://openreview.net/forum?id=SJkXfE5xx,Revisiting Classifier Two-Sample Tests,Theory; Unsupervised Learning,The goal of two-sample tests is to assess whet...,Modern binary classifiers can be easily turned...,Revisiting Classifier Two-Sample Tests explore...,25,1
13,https://openreview.net/forum?id=rkpACe1lx,HyperNetworks,Natural language processing; Deep learning; Su...,This work explores hypernetworks: an approach ...,We train a small RNN to generate weights for a...,Human-Retrieval hypernetworks leverage one net...,18,1
14,https://openreview.net/forum?id=B1YfAfcgl,Entropy-SGD: Biasing Gradient Descent Into Wid...,Deep learning; Optimization,This paper proposes a new optimization algorit...,This paper focuses on developing new optimizat...,Find local extremum points with low generaliza...,14,1
15,https://openreview.net/forum?id=B1ElR4cgg,Adversarially Learned Inference,Computer vision; Deep learning; Unsupervised L...,We introduce the adversarially learned inferen...,We present and adverserially trained generativ...,Write a program in Python that takes a list of...,17,1
16,https://openreview.net/forum?id=Bkab5dqxe,A Compositional Object-Based Approach to Learn...,Deep learning; Unsupervised Learning,"We present the Neural Physics Engine (NPE), a ...",We propose a factorization of a physical scene...,Human-computer interaction through deep reinfo...,10,1
17,https://openreview.net/forum?id=r1LXit5ee,Episodic Exploration for Deep Deterministic Po...,Deep learning; Reinforcement Learning; Games,We consider scenarios from the real-time strat...,We propose a new reinforcement learning algori...,Human: Summary: The paper proposes a novel app...,31,2
18,https://openreview.net/forum?id=SyWvgP5el,EPOpt: Learning Robust Neural Network Policies...,Reinforcement Learning; Applications,Sample complexity and safety are major challen...,An ensemble optimization approach to help tran...,Human-Agent collaboration through model ensemb...,13,1
19,https://openreview.net/forum?id=SJGCiw5gl,Pruning Convolutional Neural Networks for Reso...,Deep learning; Transfer Learning,We propose a new formulation for pruning convo...,New approach for removing unnecessary conv neu...,Pruning convolutional neural networks for reso...,21,1

In [ ]:
import evaluate

In [ ]:
predictions = ["hello there general kenobi", "foo bar foobar"]
references = [["hello there general kenobi", "hello there !"],["foo bar foobar"]]
bleu = evaluate.load("bleu")
results = bleu.compute(predictions=predictions, references=references)
print(results)

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

{'bleu': 1.0, 'precisions': [1.0, 1.0, 1.0, 1.0], 'brevity_penalty': 1.0, 'length_ratio': 1.1666666666666667, 'translation_length': 7, 'reference_length': 6}

In [ ]:
!pip install bert_score --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 58.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 34.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 37.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 75.0 MB/s eta 0:00:00

In [46]:
d = test['generated-summary'][0]
len(str(d).split())

25

In [47]:
gt = test['one_sentence_summary'][0]
len(str(gt).split())

33

In [22]:
a = Evaluation(d)

In [26]:
a.BLEU_ROUGE_Score(ground_truth=gt,mode="bleu")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

{'bleu': 0.0,
 'precisions': [0.18518518518518517, 0.0, 0.0, 0.0],
 'brevity_penalty': 0.7435670792059064,
 'length_ratio': 0.7714285714285715,
 'translation_length': 27,
 'reference_length': 35}

In [40]:
references = gt  # فقط رشته، بدون split
candidate = d

In [31]:
import evaluate

In [41]:
bleu = evaluate.load("bleu")
result = bleu.compute(predictions=[candidate], references=[references])
print(result)

{'bleu': 0.0, 'precisions': [0.18518518518518517, 0.0, 0.0, 0.0], 'brevity_penalty': 0.7435670792059064, 'length_ratio': 0.7714285714285715, 'translation_length': 27, 'reference_length': 35}